// Generated by tsbindgen - Architecture
// Namespace: Tsonic.Runtime
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './runtime/internal/index.js';

// Cross-namespace type imports for constraints
import type { Dictionary, IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator, IList, List } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.js';
import type { Action, Boolean as ClrBoolean, Double, Func, IEquatable, Int32, Nullable, Object as ClrObject, String as ClrString, Type, ValueTuple, ValueType, Void } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ArrayHelpers$instance as ArrayHelpers } from './runtime/internal/index.js';
export { DynamicObject as DynamicObject } from './runtime/internal/index.js';
export { IteratorResult_1 as IteratorResult } from './runtime/internal/index.js';
export { JSArray_1 as JSArray } from './runtime/internal/index.js';
export { JSArrayStatics$instance as JSArrayStatics } from './runtime/internal/index.js';
export { JSON$instance as JSON } from './runtime/internal/index.js';
export { JsValue$instance as JsValue } from './runtime/internal/index.js';
export { Operators$instance as Operators } from './runtime/internal/index.js';
export { Structural$instance as Structural } from './runtime/internal/index.js';
export { DictionaryAdapter_1 as DictionaryAdapter } from './runtime/internal/index.js';

// Multi-arity family value exports (arity-0 constructors/static namespaces)

// Multi-arity family sentinel (detects unspecified type parameters)
declare const __unspecified: unique symbol;
export type __ = typeof __unspecified;

export type Union<
  T1 = __,
  T2 = __,
  T3 = __,
  T4 = __,
  T5 = __,
  T6 = __,
  T7 = __,
  T8 = __,
> =
  [T3] extends [__] ? Internal.Union_2<T1, T2> :
  [T4] extends [__] ? Internal.Union_3<T1, T2, T3> :
  [T5] extends [__] ? Internal.Union_4<T1, T2, T3, T4> :
  [T6] extends [__] ? Internal.Union_5<T1, T2, T3, T4, T5> :
  [T7] extends [__] ? Internal.Union_6<T1, T2, T3, T4, T5, T6> :
  [T8] extends [__] ? Internal.Union_7<T1, T2, T3, T4, T5, T6, T7> :
  Internal.Union_8<T1, T2, T3, T4, T5, T6, T7, T8>;

